version: '3.8'

services:
  whatsapp-bot:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Persist WhatsApp sessions
      - ./sessions:/usr/src/app/.wwebjs_auth
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/clients"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  whatsapp-network:
    driver: bridge

volumes:
  sessions:
    driver: local
  logs:
    driver: local
